if always

diff --git a/.github/workflows/stepafterfail.yml b/.github/workflows/stepafterfail.yml
--- a/.github/workflows/stepafterfail.yml
+++ b/.github/workflows/stepafterfail.yml
@@ -2,12 +2,9 @@
 name: AlwaysContinue
 
 on:
-  workflow_call:
-    inputs:
-      fail:
-        required: false
-        default: false
-        type: boolean
+  push:
+    branches:
+      - main
 jobs:
   go-on:
     name: always continue # fails depending on input, shortened to have a clearer wf visualization
@@ -30,5 +27,24 @@ jobs:
         run: cat txt.log
         run: echo "Must fail!"; exit 4711
 
-
-continue-on-error: true
+  with-always:
+    name:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step One Step
+        run: echo "About to make the decision...."
+      - name: "Step Two: The failing test"
+        id: thetest
+        run:
+          - echo "some important message" > txt.log
+          - exit 42
+      - name: Happy
+        run: echo "I'm happily in between but will not run"
+      - name: Print Log in any case
+        if: always()
+        run: cat txt.log
+      - name: Print Log On Fail
+        if: always()
+        if: ${{ thetest.fail }}
+        run: cat txt.log
+        run: echo "Must not fail anymore!" #; exit 4711
